version: '3'
services:
  app:
    image: blusterg/rest-master-backend:v-0.5
    build:
      context: .
      dockerfile: Dockerfile
    command: node src/app.js
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${BACKEND_APP_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"